Debugging mail without attachment issue

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -236,6 +236,7 @@ jobs:
     - name: Extract frontend image scan report
       run: |
         tar -xzf trivy-frontend-image-report.tar.gz
+        ls -al trivy-frontend-image-report  # Debugging step to list extracted files
 
     - name: Download and extract backend image scan report
       uses: actions/download-artifact@v4
@@ -245,17 +246,11 @@ jobs:
     - name: Extract backend image scan report
       run: |
         tar -xzf trivy-backend-image-report.tar.gz
+        ls -al trivy-backend-image-report  # Debugging step to list extracted files
 
-    - name: List files before sending email
-      run: |
-        echo "Listing files before email"
-        ls -al
-        ls -al trivy-backend-image-report
-        ls -al trivy-frontend-image-report
-
-    - name: Verify files to attach
-      run: |
-        ls -al trivy-backend-fs-report.txt trivy-frontend-fs-report.txt trivy-frontend-image-report.txt trivy-backend-image-report.txt || echo "One or more files missing"
+    # - name: Verify files to attach
+    #   run: |
+    #     ls -al trivy-backend-fs-report.txt trivy-frontend-fs-report.txt trivy-frontend-image-report.txt trivy-backend-image-report.txt || echo "One or more files missing"
 
 
     - name: Prepare email body
